export const HELP = [
  'surgex — deterministic code clone detector',
  '',
  'Commands:',
  '  surgex index [paths...]          Index the codebase (default: cwd)',
  '    --verbose                      Print each indexed file',
  '    --kgram=5                      Minimum match length in tokens',
  '    --window=4                     Winnowing window size',
  '',
  '  surgex check                     Check for duplicates',
  '    (no flags)                  Uncommitted changes vs index',
  '    --all                       All indexed files (full scan)',
  '    --from=main                 Branch diff vs base ref',
  '    [files...]                  Specific files vs index',
  '    --threshold=0.75            Similarity cutoff (default: 0.75)',
  '    --min-tokens=20             Ignore small units (default: 20)',
  '    --show-code                 Show duplicated lines side by side',
  '    --json                      Machine-readable JSON output',
  '    --fail-on-found             Exit with code 1 if clones are found (CI gate)',
  '',
  '  surgex report                    Alias for `surgex check --all`',
].join('\n')
