export const HELP = [
  'surgex — deterministic code clone detector',
  '',
  'Commands:',
  '  surgex index [paths...]          Index the codebase (default: cwd)',
  '                                   Incremental: unchanged files are not re-parsed',
  '    --verbose                      Print each indexed file',
  '    --force                        Re-parse everything, ignoring the cache',
  '    --kgram=5                      Minimum match length in tokens',
  '    --window=4                     Winnowing window size',
  '    --exclude=<glob>               Skip paths (repeatable)',
  '',
  '  surgex check                     Check for duplicates',
  '    (no flags)                  Uncommitted changes vs index',
  '    --all                       All indexed files (full scan)',
  '    --from=main                 Branch diff vs base ref',
  '    [files...]                  Specific files vs index',
  '    --threshold=0.75            Similarity cutoff (default: 0.75)',
  '    --min-tokens=20             Ignore small units (default: 20)',
  '    --show-code                 Show structural matches side by side',
  '    --json                      Machine-readable JSON output',
  '    --exclude=<glob>            Skip paths (repeatable)',
  '    --fail-on-found             Exit with code 1 if clones are found (CI gate)',
  '',
  '  surgex report                    Alias for `surgex check --all`',
  '',
  'Config (surgex.json at the project root, optional):',
  '  { "presets": ["rails", "tests"], "exclude": ["engines/ui/**"],',
  '    "threshold": 0.8, "minTokens": 30 }',
  '  presets  rails  framework-owned paths (db/migrate, config/environments, bin)',
  '           tests  test and spec directories',
  '  Flags override the config; --exclude adds to it.',
].join('\n')
